<?php

declare(strict_types=1);

namespace Thevenrex\CookieJar;

class CookieJar
{
    public array $cookies = [];

    public string $fileName;
    protected string $banner = "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n";
    private string $path;

    public function __construct(FolderManager $folder)
    {
        $this->path = realpath($folder->getDirectory()) . '/';
    }

    public function setFileName(string $filename)
    {
        $this->fileName = $this->path . $filename;

        return $this;
    }

    public function getFileName()
    {
        return $this->fileName;
    }

    public function add(Cookie $cookie)
    {
        $this->cookies[] = $cookie->get();

        return $this;
    }

    public function get()
    {
        $cookie = $this->banner;

        foreach ($this->cookies as $value) {
            $cookie .= $value . "\n";
        }

        return $cookie;
    }

    public function save(): void
    {
        file_put_contents(
            $this->fileName,
            $this->get()
        );
    }
}
